### ISSUE TITLE
Recursive log dirs?

### ISSUE THREAD

**Issue by ollenordesjo** [NVIDIA/runx#16]
pip install runx installs v.0.0.11.

This breaks the log functionality somehow, and I'm seeing:

```
Copying codebase to ../logs/sweep/spectral-okapi_2021.07.12_15.16 ...
Running job sweep_spectral-okapi_2021.07.12_15.16
cd ../logs/sweep/spectral-okapi_2021.07.12_15.16/code; PYTHONPATH=  python testrunx.py --lr 0.01 --solver first --logdir ..//logs
/bin/sh: 1: cd: can't cd to ../logs/sweep/spectral-okapi_2021.07.12_15.16/code
python: can't open file 'testrunx.py': [Errno 2] No such file or directory

Copying codebase to ../logs/sweep/teal-trogon_2021.07.12_15.16 ...
Running job sweep_teal-trogon_2021.07.12_15.16
cd ../logs/sweep/teal-trogon_2021.07.12_15.16/code; PYTHONPATH=  python testrunx.py --lr 0.01 --solver second --logdir ..//logs
/bin/sh: 1: cd: can't cd to ../logs/sweep/teal-trogon_2021.07.12_15.16/code
python: can't open file 'testrunx.py': [Errno 2] No such file or directory

Copying codebase to ../logs/sweep/garrulous-wombat_2021.07.12_15.16 ...
Running job sweep_garrulous-wombat_2021.07.12_15.16
cd ../logs/sweep/garrulous-wombat_2021.07.12_15.16/code; PYTHONPATH=  python testrunx.py --lr 0.02 --solver first --logdir ..//logs
/bin/sh: 1: cd: can't cd to ../logs/sweep/garrulous-wombat_2021.07.12_15.16/code
python: can't open file 'testrunx.py': [Errno 2] No such file or directory

Copying codebase to ../logs/sweep/lavender-prawn_2021.07.12_15.16 ...
Running job sweep_lavender-prawn_2021.07.12_15.16
cd ../logs/sweep/lavender-prawn_2021.07.12_15.16/code; PYTHONPATH=  python testrunx.py --lr 0.02 --solver second --logdir ..//logs
/bin/sh: 1: cd: can't cd to ../logs/sweep/lavender-prawn_2021.07.12_15.16/code
python: can't open file 'testrunx.py': [Errno 2] No such file or directory

```

Looking at ../logs, I'm seeing recursive paths like this one:

```
../logs/sweep/logs/sweep/logs/sweep/logs/sweep/complex-mongrel_2021.07.12_15.06/submit_cmd.sh
```

Here is my python script (testrunx.py)

``` 
import sys
print(sys.argv)
```

And here is my sweep.yml:

```
CMD: 'python testrunx.py'

HPARAMS:
        lr: [0.01, 0.02]
        solver: ['first', 'second']
        logdir: '..//logs'
```

Installing version 0.0.5 fixes the problem.

**Comment by ajtao** [comment]
Hi, did you create a .runx file in which you define a LOGROOT? I would do so, and make the path absolute. Maybe try that.

**Comment by ollenordesjo** [comment]
Yep, I tried to do so, and made the path absolute now as well. When running (on v.0.0.11), I'm getting something similar to this:

```
 python -m runx.runx sweep.yml -i
Copying codebase to /home/.../onordesjo/git/runxtest/sweep/economic-lyrebird_2021.07.13_13.17 ...
Traceback (most recent call last):
  File "/home/.../onordesjo/miniconda3/envs/sequences/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/.../onordesjo/miniconda3/envs/sequences/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/.../onordesjo/miniconda3/envs/sequences/lib/python3.8/site-packages/runx/runx.py", line 402, in <module>
    main()
  File "/home/.../onordesjo/miniconda3/envs/sequences/lib/python3.8/site-packages/runx/runx.py", line 395, in main
    run_experiment(args.exp_yml)
  File "/home/.../onordesjo/miniconda3/envs/sequences/lib/python3.8/site-packages/runx/runx.py", line 390, in run_experiment
    run_yaml(experiment, runroot)
  File "/home/.../onordesjo/miniconda3/envs/sequences/lib/python3.8/site-packages/runx/runx.py", line 345, in run_yaml
    copy_code(logdir, runroot, code_ignore_patterns)
  File "/home/.../onordesjo/miniconda3/envs/sequences/lib/python3.8/site-packages/runx/runx.py", line 216, in copy_code
    copytree(runroot, tgt_code_dir, ignore=code_ignore_patterns)
  File "/home/.../onordesjo/miniconda3/envs/sequences/lib/python3.8/shutil.py", line 547, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/home/.../onordesjo/miniconda3/envs/sequences/lib/python3.8/shutil.py", line 504, in _copytree
    raise Error(errors)
shutil.Error: [('/home/.../onordesjo/git/runxtest/sweep/economic-lyrebird_2021.07.13_13.17/code/sweep/economic-lyrebird_2021.07.13_13.17/code/sweep/economic-lyrebird_2021.07.13_13.17/code/sweep/economic-lyrebird_2021.07.13_13.17/code/sweep/economic-lyrebird_2021.07.13_13.17/code/sweep/economic-lyrebird_2021.07.13_13.17/code/sweep/economic-lyrebird_2021.07.13_13.17/code/sweep/economic-lyrebird_2021.07.13_13.17/code/sweep/economic-lyrebird_2021.07.13_13.17/code/sweep/economic-lyrebird_2021.07.13_13.17/code/sweep/economic-lyrebird_2021.07.13_13.17...
...
economic-lyrebird_2021.07.13_13.17/code/sweep'")]
```

**Comment by ajtao** [comment]
It's not clear to me why there's `...` in your LOGROOT path. Maybe you could show your .runx file?
